### ISSUE TITLE
TypeError: Cannot read property 'typeName' of undefined at MessageParser.parse

### ISSUE THREAD

**Issue by munawwarhussain** [enricostara/telegram-mt-node#3]
[ERROR] Tue, 23 Jun 2015 07:28:10 GMT  ConstructorBuilder.registry Unable to retrieve a Type by Id [e033ae7d]
[ERROR] Tue, 23 Jun 2015 07:28:10 GMT  net.RpcChannel Unable to deserialize response d701cfc1df2f3858d93829d3199ccada1c27fdb22e38b9e027bdcd2abd2c399adf0258d1af4df5bf315e2f7dbdf2a7f5e4f18660f07c211db9551ac690ca558f41f3487ba5cc1e5277971edacdb1408d2fc7e8500047a74d288d76f50309f968d99e304cd9820b1bd909b4e79eb1e3750f007c71bf5f46cf9860b1ef2c24e1a8137dca4aac8d316d1405caf2fb553013466117b67582b0e89766c42551df7111668b4c6b0cd96fa9ec594a835cb51b47ffcb60893c9a9ce605400b34ef30f355d113bc7eb6700c244c221d9a596a6f1af8dde079f7f8959d20b16206a8caf9ead8d70bab07c534f4e9a168bf13eec56da054dc3111cdeab967dd2445d577e5070d5e90e884a79a5724f06c3e46ea83d546302c0c06967769 from mtproto.type.Msgs_ack due to Error: Unable to retrieve a Type by Id [e033ae7d]
    at Function.requireTypeFromBuffer (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:332:15)
    at deserialize (eval at createConstructor (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:115:27), <anonymous>:27:33)
    at deserialize (eval at createConstructor (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:115:27), <anonymous>:32:79)
    at deserialize (eval at createConstructor (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:115:27), <anonymous>:28:80)
    at EncryptedMessage.deserialize (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/message/encrypted-message.js:151:89)
    at EncryptedRpcChannel._deserializeResponse (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/net/encrypted-rpc-channel.js:173:99)
    at /home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/net/rpc-channel.js:64:35
    at IncomingMessage.onData (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/net/http-connection.js:101:25)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:95:17) 
[ERROR] Tue, 23 Jun 2015 07:28:10 GMT  net.EncryptedRpcChannel Error: Unable to retrieve a Type by Id [e033ae7d]
    at Function.requireTypeFromBuffer (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:332:15)
    at deserialize (eval at createConstructor (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:115:27), <anonymous>:27:33)
    at deserialize (eval at createConstructor (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:115:27), <anonymous>:32:79)
    at deserialize (eval at createConstructor (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:115:27), <anonymous>:28:80)
    at EncryptedMessage.deserialize (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/message/encrypted-message.js:151:89)
    at EncryptedRpcChannel._deserializeResponse (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/net/encrypted-rpc-channel.js:173:99)
    at /home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/net/rpc-channel.js:64:35
    at IncomingMessage.onData (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/net/http-connection.js:101:25)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:95:17)
[INFO] Tue, 23 Jun 2015 07:28:10 GMT  net.EncryptedRpcChannel Call of 'mtproto.type.Msgs_ack' took undefinedms

/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/message/message-parser.js:22
    switch (message.typeName) {
                   ^
TypeError: Cannot read property 'typeName' of undefined
    at MessageParser.parse (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/message/message-parser.js:22:20)
    at /home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/net/encrypted-rpc-channel.js:163:26
    at /home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/net/rpc-channel.js:77:21
    at IncomingMessage.onData (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/net/http-connection.js:101:25)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (_stream_readable.js:765:14)
    at IncomingMessage.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)

**Comment by enricostara** [comment]
a bit of context? :)

**Comment by munawwarhussain** [comment]
when the response was suppose received from server for getNearestDc

**Comment by enricostara** [comment]
the test for "getNearestDc" is working as far as i know, write the example that you running

**Comment by munawwarhussain** [comment]
var client = require('./client-proxy');
var Promise = require("es6-promise").Promise
var readline = require('readline');

var TEST_PHONE_NUMBER = '+919769339254'

var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});


var clientPromise = client.createClientForNewUser().then(function(){
	console.log('checking')
    // client.checkPhone('+919687545544').then(function(result){
	   //  if(!result.registered){
	   //      console.log('client not registered sending code')
	   //  }else{
	   //      console.log('client already registered...')
	   //  }
	    client.sendCodeToPhone(TEST_PHONE_NUMBER)
	    rl.question("enter phone code : ", function(answer) {
			// TODO: Log the answer in a database
			console.log("phone code is :", answer);
			rl.close();
			client.signIn(TEST_PHONE_NUMBER, answer , function(result){
				console.log('sign In successful.')
				client.getContacts('hhvv',function(result){
					console.log('gotContacts : ');
					// for (var i = 0; i < result.contacts.length; i++) {
     //    				var userID = result.contacts[i].user_id; 
     //    				console.log('User id : '+userID);
					// }
				})
			})
		});
    // });
});

i m using the client proxy from termgram

**Comment by badoualy** [comment]
Using the connectionType: 'TCP' seems to avoid this error

**Comment by enricostara** [comment]
@munawwarhussain  could you update the library to see if last changes fix the issue now?
