### ISSUE TITLE
ConstructorBuilder.registry Unable to retrieve a Type by Name [api.type.Update]

### ISSUE THREAD

**Issue by munawwarhussain** [enricostara/telegram-mt-node#4]
[ERROR] Mon, 22 Jun 2015 04:18:24 GMT  ConstructorBuilder.registry Unable to retrieve a Type by Name [api.type.Update]
[ERROR] Mon, 22 Jun 2015 04:18:24 GMT  net.RpcChannel Unable to deserialize response 756172d4e93792d0133d7243c571cf0c58fe029f634b9825891aaec040bb1b1de0b504227196cc72bca84e5f3951a2bf548357483101d5fe10839a26337581d48bd33933fde494fc45a53ec5ed55164e57fa4e4d866f9363b823581a7910cf864f22ad3d645b2bff3af5d292af6d5e5439fba63ea27443a982773125e251ace46c45f9b95964ea03 from mtproto.type.Msgs_ack due to Error: Unable to retrieve a Type by Name [api.type.Update]
    at Function.requireTypeByName (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:358:15)
    at Object.requireTypeByName (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-tl-node/lib/builder/type-builder.js:125:31)
    at TypeVector.manageType (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-tl-node/lib/type-vector.js:50:23)
    at new TypeVector (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-tl-node/lib/type-vector.js:34:16)
    at deserialize (eval at createConstructor (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:115:27), <anonymous>:27:14)
    at deserialize (eval at createConstructor (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:115:27), <anonymous>:32:79)
    at deserialize (eval at createConstructor (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:115:27), <anonymous>:28:80)
    at EncryptedMessage.deserialize (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/message/encrypted-message.js:151:89)
    at EncryptedRpcChannel._deserializeResponse (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/net/encrypted-rpc-channel.js:173:99)
    at /home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/net/rpc-channel.js:64:35 
[ERROR] Mon, 22 Jun 2015 04:18:24 GMT  net.EncryptedRpcChannel Error: Unable to retrieve a Type by Name [api.type.Update]
    at Function.requireTypeByName (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:358:15)
    at Object.requireTypeByName (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-tl-node/lib/builder/type-builder.js:125:31)
    at TypeVector.manageType (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-tl-node/lib/type-vector.js:50:23)
    at new TypeVector (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-tl-node/lib/type-vector.js:34:16)
    at deserialize (eval at createConstructor (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:115:27), <anonymous>:27:14)
    at deserialize (eval at createConstructor (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:115:27), <anonymous>:32:79)
    at deserialize (eval at createConstructor (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:115:27), <anonymous>:28:80)
    at EncryptedMessage.deserialize (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/message/encrypted-message.js:151:89)
    at EncryptedRpcChannel._deserializeResponse (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/net/encrypted-rpc-channel.js:173:99)
    at /home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/net/rpc-channel.js:64:35
[INFO] Mon, 22 Jun 2015 04:18:24 GMT  net.EncryptedRpcChannel Call of 'mtproto.type.Msgs_ack' took undefinedms

/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/message/message-parser.js:22
    switch (message.typeName) {
                   ^
TypeError: Cannot read property 'typeName' of undefined
    at MessageParser.parse (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/message/message-parser.js:22:20)
    at /home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/net/encrypted-rpc-channel.js:163:26
    at /home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/net/rpc-channel.js:77:21
    at IncomingMessage.onData (/home/munawwarshelia/Desktop/random/telegram.link/node_modules/telegram-mt-node/lib/net/http-connection.js:101:25)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (_stream_readable.js:765:14)
    at IncomingMessage.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)

**Comment by badoualy** [comment]
Any progress on this ?

**Comment by enricostara** [comment]
Should be solved, see #5
